[build]
publish = "build"
command = "npm run build"

[[redirects]]
from = "https://ivans-rv.idubrov.name/*"
to = "https://ivan.aero/:splat"
status = 301
force = true

[[headers]]
for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline';font-src 'self' fonts.gstatic.com;style-src 'self' 'unsafe-inline' fonts.googleapis.com;frame-src www.youtube-nocookie.com"
